export const RECEIVE_USERS = 'RECEIVE_USERS'
// export const GET_USER = 'GET_USER'

//APIS
export const ApiConstants = {
    RECEIVE_APIS: 'RECEIVE_APIS',
    RECEIVE_API: 'RECEIVE_API',
    NEW_API: 'NEW_API',
    UPDATE_API: 'UPDATE_API',
    SAVE_API: 'SAVE_API',
    RESET_API: 'RESET_API',
    API_SOURCE: 'API_SOURCE',
    CLEAR_API_SOURCE: 'CLEAR_API_SOURCE',
    FETCHING_API_SOURCE: 'FETCHING_API_SOURCE',
    FINISH_FETCHING_API_SOURCE: 'FINISH_FETCHING_API_SOURCE',
    API_NOTIFICATION: 'API_NOTIFICATION'
}

//AUTH
export const AuthConstants = {
    GET_USER_LOGIN: 'GET_USER_LOGIN',
    LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    AUTH_LOADING: 'AUTH_LOADING',
    AUTH_LOADING_FINISH: 'AUTH_LOADING_FINISH'
}

//ENVIRONMENTS
export const EnvironmentConstants = {
    GET_ENVIRONMENTS: 'GET_ENVIRONMENTS',
    CLEAR_ENVIRONMENTS: 'CLEAR_ENVIRONMENTS',
    GET_ENVIRONMENT: 'GET_ENVIRONMENT',
    CLEAR_ENVIRONMENT: 'CLEAR_ENVIRONMENT',
    ENVIRONMENT_LOADING: 'ENVIRONMENT_LOADING',
    ENVIRONMENT_LOADING_FINISH: 'ENVIRONMENT_LOADING_FINISH',
    ENVIRONMENT_NOTIFICATION: 'ENVIRONMENT_NOTIFICATION'
}

//DEVELOPERS
export const DeveloperConstants = {
    GET_DEVELOPERS: 'GET_DEVELOPERS',
    CLEAR_DEVELOPERS: 'CLEAR_DEVELOPERS',
    GET_DEVELOPER: 'GET_DEVELOPER',
    CLEAR_DEVELOPER: 'CLEAR_DEVELOPER',
    DEVELOPER_LOADING: 'DEVELOPER_LOADING',
    DEVELOPER_LOADING_FINISH: 'DEVELOPER_LOADING_FINISH',
    DEVELOPER_SOURCE: 'DEVELOPER_SOURCE',
    CLEAR_DEVELOPER_SOURCE: 'CLEAR_DEVELOPER_SOURCE',
    FETCHING_DEVELOPER_SOURCE: 'FETCHING_DEVELOPER_SOURCE',
    FINISH_FETCHING_DEVELOPER_SOURCE: 'FINISH_FETCHING_DEVELOPER_SOURCE',
    DEVELOPER_NOTIFICATION: 'DEVELOPER_NOTIFICATION'
}

//RESOURCES
export const ResourceConstants = {
    ALL_RESOURCES: 'ALL_RESOURCES',
    UPDATE_RESOURCES_WITH_OPERATIONS: 'UPDATE_RESOURCES_WITH_OPERATIONS',
    CLEAR_RESOURCES: 'CLEAR_RESOURCES',
    VISIBLE_MODAL: 'VISIBLE_MODAL',
    RESET_RESOURCE: 'RESET_RESOURCE',
    GET_RESOURCE: 'GET_RESOURCE',
    INIT_LOADING: 'INIT_LOADING',
    FINISH_LOADING: 'FINISH_LOADING'
}

//OPERATIONS
export const OperationConstants = {
    OPERATIONS_FROM_RESOURCES: 'OPERATIONS_FROM_RESOURCES',
    CLEAR_OPERATIONS: 'CLEAR_OPERATIONS',
    ADD_OPERATIONS: 'ADD_OPERATIONS',
    INIT_LOADING: 'INIT_LOADING',
    FINISH_LOADING: 'FINISH_LOADING',
    VISIBLE_MODAL_OPERATION: 'VISIBLE_MODAL_OPERATION',
    RESET_OPERATION: 'RESET_OPERATION',
    GET_OPERATION: 'GET_OPERATION'
}

//APPS
export const AppConstants = {
    GET_APPS: 'GET_APPS',
    CLEAR_APPS: 'CLEAR_APPS',
    GET_APP: 'GET_APP',
    CLEAR_APP: 'CLEAR_APP',
    APP_LOADING: 'APP_LOADING',
    APP_LOADING_FINISH: 'APP_LOADING_FINISH',
    APP_NOTIFICATION: 'APP_NOTIFICATION',
    APP_SOURCE: 'APP_SOURCE',
    CLEAR_APP_SOURCE: 'CLEAR_APP_SOURCE',
    FETCHING_APP_SOURCE: 'FETCHING_APP_SOURCE',
    FINISH_FETCHING_APP_SOURCE: 'FINISH_FETCHING_APP_SOURCE'
}

//PLANS
export const PlanConstants = {
    GET_PLANS: 'GET_PLANS',
    CLEAR_PLANS: 'CLEAR_PLANS',
    GET_PLAN: 'GET_PLAN',
    CLEAR_PLAN: 'CLEAR_PLAN',
    PLAN_LOADING: 'PLAN_LOADING',
    PLAN_LOADING_FINISH: 'PLAN_LOADING_FINISH',
    PLAN_NOTIFICATION: 'PLAN_NOTIFICATION'
}

//ACCESS-TOKENS
export const AccessTokenConstants = {
    GET_ACCESS_TOKENS: 'GET_ACCESS_TOKENS',
    CLEAR_ACCESS_TOKENS: 'CLEAR_ACCESS_TOKENS',
    GET_ACCESS_TOKEN: 'GET_ACCESS_TOKEN',
    CLEAR_ACCESS_TOKEN: 'CLEAR_ACCESS_TOKEN',
    ACCESS_TOKEN_LOADING: 'ACCESS_TOKEN_LOADING',
    ACCESS_TOKEN_LOADING_FINISH: 'ACCESS_TOKEN_LOADING_FINISH',
    ACCESS_TOKEN_NOTIFICATION: 'ACCESS_TOKEN_NOTIFICATION'
}

//INTERCEPTORS
export const InterceptorConstants = {
    GET_INTERCEPTORS: 'GET_INTERCEPTORS',
    GET_INTERCEPTORS_TYPES: 'GET_INTERCEPTORS_TYPES',
    CLEAR_INTERCEPTORS_TYPES: 'CLEAR_INTERCEPTORS_TYPES',
    CLEAR_INTERCEPTORS: 'CLEAR_INTERCEPTORS',
    GET_INTERCEPTOR: 'GET_INTERCEPTOR',
    CLEAR_INTERCEPTOR: 'CLEAR_INTERCEPTOR',
    INTERCEPTOR_LOADING: 'INTERCEPTOR_LOADING',
    INTERCEPTOR_LOADING_FINISH: 'INTERCEPTOR_LOADING_FINISH',
    INTERCEPTOR_NOTIFICATION: 'INTERCEPTOR_NOTIFICATION'
}

export const QueueConstants = {
    RECEIVE_QUEUE: 'RECEIVE_QUEUE',
    PROCESS_QUEUE: 'PROCESS_QUEUE',
    ERROR_QUEUE: 'ERROR_QUEUE',
    CLEAR_QUEUE: 'CLEAR_QUEUE'
}

//Users
export const UserConstants = {
    GET_USERS: 'GET_USERS',
    CLEAR_USERS: 'CLEAR_USERS',
    GET_USER: 'GET_USER',
    CLEAR_USER: 'CLEAR_USER',
    USER_LOADING: 'USER_LOADING',
    USER_LOADING_FINISH: 'USER_LOADING_FINISH',
    USER_NOTIFICATION: 'USER_NOTIFICATION'
}

//Roles
export const RoleConstants = {
    GET_ROLES: 'GET_ROLES',
    CLEAR_ROLES: 'CLEAR_ROLES',
    GET_ROLE: 'GET_ROLE',
    CLEAR_ROLE: 'CLEAR_ROLE',
    ROLE_LOADING: 'ROLE_LOADING',
    ROLE_LOADING_FINISH: 'ROLE_LOADING_FINISH',
    ROLE_NOTIFICATION: 'ROLE_NOTIFICATION'
}

//Middlewares
export const MiddlewaresConstants = {
    GET_MIDDLEWARES: 'GET_MIDDLEWARES',
    GET_MIDDLEWARE: 'GET_MIDDLEWARE',
    MIDDLEWARE_LOADING: 'MIDDLEWARE_LOADING',
    MIDDLEWARE_LOADING_FINISH: 'MIDDLEWARE_LOADING_FINISH',
    MIDDLEWARE_NOTIFICATION: 'MIDDLEWARE_NOTIFICATION',
    MIDDLEWARE_DOWNLOAD: 'MIDDLEWARE_DOWNLOAD'
}

export const TraceConstants = {
    GET_TRACES: 'GET_TRACES',
    GET_TRACE: 'GET_TRACE',
    TRACE_LOADING: 'TRACE_LOADING',
    TRACE_LOADING_FINISH: 'TRACE_LOADING_FINISH',
    TRACE_NOTIFICATION: 'TRACE_NOTIFICATION'
}

export const CacheConstants = {
    CLEAR_CACHE: 'CLEAR_CACHE',
    CACHE_LOADING: 'CACHE_LOADING',
    CACHE_LOADING_FINISH: 'CACHE_LOADING_FINISH',
    CACHE_NOTIFICATION: 'CACHE_NOTIFICATION'
}