export const privileges = {
    PRIVILEGE_READ_ACCESSTOKEN: 'READ_ACCESSTOKEN',
    PRIVILEGE_CREATE_ACCESSTOKEN: 'CREATE_ACCESSTOKEN',
    PRIVILEGE_UPDATE_ACCESSTOKEN: 'UPDATE_ACCESSTOKEN',
    PRIVILEGE_DELETE_ACCESSTOKEN: 'DELETE_ACCESSTOKEN',

    PRIVILEGE_READ_API: 'READ_API',
    PRIVILEGE_CREATE_API: 'CREATE_API',
    PRIVILEGE_UPDATE_API: 'UPDATE_API',
    PRIVILEGE_DELETE_API: 'DELETE_API',

    PRIVILEGE_READ_MIDDLEWARE: 'READ_MIDDLEWARE',
    PRIVILEGE_CREATE_MIDDLEWARE: 'CREATE_MIDDLEWARE',
    PRIVILEGE_UPDATE_MIDDLEWARE: 'UPDATE_MIDDLEWARE',
    PRIVILEGE_DELETE_MIDDLEWARE: 'DELETE_MIDDLEWARE',

    PRIVILEGE_READ_APP: 'READ_APP',
    PRIVILEGE_CREATE_APP: 'CREATE_APP',
    PRIVILEGE_UPDATE_APP: 'UPDATE_APP',
    PRIVILEGE_DELETE_APP: 'DELETE_APP',

    PRIVILEGE_READ_CACHES: 'READ_CACHES',
    PRIVILEGE_DELETE_CACHES: 'DELETE_CACHES',

    PRIVILEGE_READ_DEVELOPER: 'READ_DEVELOPER',
    PRIVILEGE_CREATE_DEVELOPER: 'CREATE_DEVELOPER',
    PRIVILEGE_UPDATE_DEVELOPER: 'UPDATE_DEVELOPER',
    PRIVILEGE_DELETE_DEVELOPER: 'DELETE_DEVELOPER',

    PRIVILEGE_READ_ENVIRONMENT: 'READ_ENVIRONMENT',
    PRIVILEGE_CREATE_ENVIRONMENT: 'CREATE_ENVIRONMENT',
    PRIVILEGE_UPDATE_ENVIRONMENT: 'UPDATE_ENVIRONMENT',
    PRIVILEGE_DELETE_ENVIRONMENT: 'DELETE_ENVIRONMENT',

    PRIVILEGE_READ_INTERCEPTOR: 'READ_INTERCEPTOR',
    PRIVILEGE_CREATE_INTERCEPTOR: 'CREATE_INTERCEPTOR',
    PRIVILEGE_UPDATE_INTERCEPTOR: 'UPDATE_INTERCEPTOR',
    PRIVILEGE_DELETE_INTERCEPTOR: 'DELETE_INTERCEPTOR',
    PRIVILEGE_REFRESH_INTERCEPTOR: 'REFRESH_INTERCEPTOR',

    PRIVILEGE_READ_OPERATION: 'READ_OPERATION',
    PRIVILEGE_CREATE_OPERATION: 'CREATE_OPERATION',
    PRIVILEGE_UPDATE_OPERATION: 'UPDATE_OPERATION',
    PRIVILEGE_DELETE_OPERATION: 'DELETE_OPERATION',
    PRIVILEGE_REFRESH_OPERATION: 'REFRESH_OPERATION',

    PRIVILEGE_READ_PLAN: 'READ_PLAN',
    PRIVILEGE_CREATE_PLAN: 'CREATE_PLAN',
    PRIVILEGE_UPDATE_PLAN: 'UPDATE_PLAN',
    PRIVILEGE_DELETE_PLAN: 'DELETE_PLAN',

    PRIVILEGE_READ_PRIVILEGE: 'READ_PRIVILEGE',

    PRIVILEGE_READ_RESOURCE: 'READ_RESOURCE',
    PRIVILEGE_CREATE_RESOURCE: 'CREATE_RESOURCE',
    PRIVILEGE_UPDATE_RESOURCE: 'UPDATE_RESOURCE',
    PRIVILEGE_DELETE_RESOURCE: 'DELETE_RESOURCE',
    PRIVILEGE_REFRESH_RESOURCE: 'REFRESH_RESOURCE',

    PRIVILEGE_READ_ROLE: 'READ_ROLE',
    PRIVILEGE_CREATE_ROLE: 'CREATE_ROLE',
    PRIVILEGE_UPDATE_ROLE: 'UPDATE_ROLE',
    PRIVILEGE_DELETE_ROLE: 'DELETE_ROLE',

    PRIVILEGE_READ_USER: 'READ_USER',
    PRIVILEGE_CREATE_USER: 'CREATE_USER',
    PRIVILEGE_UPDATE_USER: 'UPDATE_USER',
    PRIVILEGE_DELETE_USER: 'DELETE_USER',

    PRIVILEGE_READ_PROVIDER: 'READ_PROVIDER',
    PRIVILEGE_CREATE_PROVIDER: 'CREATE_PROVIDER',
    PRIVILEGE_UPDATE_PROVIDER: 'UPDATE_PROVIDER',
    PRIVILEGE_DELETE_PROVIDER: 'DELETE_PROVIDER',

    PRIVILEGE_READ_TRACES: 'READ_TRACES',
    PRIVILEGE_CREATE_TRACES: 'CREATE_TRACES',
    PRIVILEGE_UPDATE_TRACES: 'UPDATE_TRACES',
    PRIVILEGE_DELETE_TRACES: 'DELETE_TRACES',

    PRIVILEGE_READ_LDAP: 'READ_LDAP',
    PRIVILEGE_UPDATE_LDAP: 'UPDATE_LDAP',

    PRIVILEGE_READ_SCOPE: 'READ_SCOPE',
    PRIVILEGE_CREATE_SCOPE: 'CREATE_SCOPE',
    PRIVILEGE_UPDATE_SCOPE: 'UPDATE_SCOPE',
    PRIVILEGE_DELETE_SCOPE: 'DELETE_SCOPE'
}