const PRIVILEGE_READ_ACCESSTOKEN = 'READ_ACCESSTOKEN'
const PRIVILEGE_CREATE_ACCESSTOKEN = 'CREATE_ACCESSTOKEN'
const PRIVILEGE_UPDATE_ACCESSTOKEN = 'UPDATE_ACCESSTOKEN'
const PRIVILEGE_DELETE_ACCESSTOKEN = 'DELETE_ACCESSTOKEN'

const PRIVILEGE_READ_API = 'READ_API'
const PRIVILEGE_CREATE_API = 'CREATE_API'
const PRIVILEGE_UPDATE_API = 'UPDATE_API'
const PRIVILEGE_DELETE_API = 'DELETE_API'

const PRIVILEGE_READ_MIDDLEWARE = 'READ_MIDDLEWARE'
const PRIVILEGE_CREATE_MIDDLEWARE = 'CREATE_MIDDLEWARE'
const PRIVILEGE_UPDATE_MIDDLEWARE = 'UPDATE_MIDDLEWARE'
const PRIVILEGE_DELETE_MIDDLEWARE = 'DELETE_MIDDLEWARE'

const PRIVILEGE_READ_APP = 'READ_APP'
const PRIVILEGE_CREATE_APP = 'CREATE_APP'
const PRIVILEGE_UPDATE_APP = 'UPDATE_APP'
const PRIVILEGE_DELETE_APP = 'DELETE_APP'

const PRIVILEGE_READ_CACHES = 'READ_CACHES'
const PRIVILEGE_DELETE_CACHES = 'DELETE_CACHES'

const PRIVILEGE_READ_DEVELOPER = 'READ_DEVELOPER'
const PRIVILEGE_CREATE_DEVELOPER = 'CREATE_DEVELOPER'
const PRIVILEGE_UPDATE_DEVELOPER = 'UPDATE_DEVELOPER'
const PRIVILEGE_DELETE_DEVELOPER = 'DELETE_DEVELOPER'

const PRIVILEGE_READ_ENVIRONMENT = 'READ_ENVIRONMENT'
const PRIVILEGE_CREATE_ENVIRONMENT = 'CREATE_ENVIRONMENT'
const PRIVILEGE_UPDATE_ENVIRONMENT = 'UPDATE_ENVIRONMENT'
const PRIVILEGE_DELETE_ENVIRONMENT = 'DELETE_ENVIRONMENT'

const PRIVILEGE_READ_INTERCEPTOR = 'READ_INTERCEPTOR'
const PRIVILEGE_CREATE_INTERCEPTOR = 'CREATE_INTERCEPTOR'
const PRIVILEGE_UPDATE_INTERCEPTOR = 'UPDATE_INTERCEPTOR'
const PRIVILEGE_DELETE_INTERCEPTOR = 'DELETE_INTERCEPTOR'
const PRIVILEGE_REFRESH_INTERCEPTOR = 'REFRESH_INTERCEPTOR'

const PRIVILEGE_READ_OPERATION = 'READ_OPERATION'
const PRIVILEGE_CREATE_OPERATION = 'CREATE_OPERATION'
const PRIVILEGE_UPDATE_OPERATION = 'UPDATE_OPERATION'
const PRIVILEGE_DELETE_OPERATION = 'DELETE_OPERATION'
const PRIVILEGE_REFRESH_OPERATION = 'REFRESH_OPERATION'

const PRIVILEGE_READ_PLAN = 'READ_PLAN'
const PRIVILEGE_CREATE_PLAN = 'CREATE_PLAN'
const PRIVILEGE_UPDATE_PLAN = 'UPDATE_PLAN'
const PRIVILEGE_DELETE_PLAN = 'DELETE_PLAN'

const PRIVILEGE_READ_PRIVILEGE = 'READ_PRIVILEGE'

const PRIVILEGE_READ_RESOURCE = 'READ_RESOURCE'
const PRIVILEGE_CREATE_RESOURCE = 'CREATE_RESOURCE'
const PRIVILEGE_UPDATE_RESOURCE = 'UPDATE_RESOURCE'
const PRIVILEGE_DELETE_RESOURCE = 'DELETE_RESOURCE'
const PRIVILEGE_REFRESH_RESOURCE = 'REFRESH_RESOURCE'

const PRIVILEGE_READ_ROLE = 'READ_ROLE'
const PRIVILEGE_CREATE_ROLE = 'CREATE_ROLE'
const PRIVILEGE_UPDATE_ROLE = 'UPDATE_ROLE'
const PRIVILEGE_DELETE_ROLE = 'DELETE_ROLE'

const PRIVILEGE_READ_USER = 'READ_USER'
const PRIVILEGE_CREATE_USER = 'CREATE_USER'
const PRIVILEGE_UPDATE_USER = 'UPDATE_USER'
const PRIVILEGE_DELETE_USER = 'DELETE_USER'

const PRIVILEGE_READ_PROVIDER = 'READ_PROVIDER'
const PRIVILEGE_CREATE_PROVIDER = 'CREATE_PROVIDER'
const PRIVILEGE_UPDATE_PROVIDER = 'UPDATE_PROVIDER'
const PRIVILEGE_DELETE_PROVIDER = 'DELETE_PROVIDER'

const PRIVILEGE_READ_TRACES = 'READ_TRACES'
const PRIVILEGE_CREATE_TRACES = 'CREATE_TRACES'
const PRIVILEGE_UPDATE_TRACES = 'UPDATE_TRACES'
const PRIVILEGE_DELETE_TRACES = 'DELETE_TRACES'

export {
    PRIVILEGE_READ_ACCESSTOKEN,
    PRIVILEGE_CREATE_ACCESSTOKEN,
    PRIVILEGE_UPDATE_ACCESSTOKEN,
    PRIVILEGE_DELETE_ACCESSTOKEN,
    PRIVILEGE_READ_API,
    PRIVILEGE_CREATE_API,
    PRIVILEGE_UPDATE_API,
    PRIVILEGE_DELETE_API,
    PRIVILEGE_READ_MIDDLEWARE,
    PRIVILEGE_CREATE_MIDDLEWARE,
    PRIVILEGE_UPDATE_MIDDLEWARE,
    PRIVILEGE_DELETE_MIDDLEWARE,
    PRIVILEGE_READ_APP,
    PRIVILEGE_CREATE_APP,
    PRIVILEGE_UPDATE_APP,
    PRIVILEGE_DELETE_APP,
    PRIVILEGE_READ_CACHES,
    PRIVILEGE_DELETE_CACHES,
    PRIVILEGE_READ_DEVELOPER,
    PRIVILEGE_CREATE_DEVELOPER,
    PRIVILEGE_UPDATE_DEVELOPER,
    PRIVILEGE_DELETE_DEVELOPER,
    PRIVILEGE_READ_ENVIRONMENT,
    PRIVILEGE_CREATE_ENVIRONMENT,
    PRIVILEGE_UPDATE_ENVIRONMENT,
    PRIVILEGE_DELETE_ENVIRONMENT,
    PRIVILEGE_READ_INTERCEPTOR,
    PRIVILEGE_CREATE_INTERCEPTOR,
    PRIVILEGE_UPDATE_INTERCEPTOR,
    PRIVILEGE_DELETE_INTERCEPTOR,
    PRIVILEGE_REFRESH_INTERCEPTOR,
    PRIVILEGE_READ_OPERATION,
    PRIVILEGE_CREATE_OPERATION,
    PRIVILEGE_UPDATE_OPERATION,
    PRIVILEGE_DELETE_OPERATION,
    PRIVILEGE_REFRESH_OPERATION,
    PRIVILEGE_READ_PLAN,
    PRIVILEGE_CREATE_PLAN,
    PRIVILEGE_UPDATE_PLAN,
    PRIVILEGE_DELETE_PLAN,
    PRIVILEGE_READ_PRIVILEGE,
    PRIVILEGE_READ_RESOURCE,
    PRIVILEGE_CREATE_RESOURCE,
    PRIVILEGE_UPDATE_RESOURCE,
    PRIVILEGE_DELETE_RESOURCE,
    PRIVILEGE_REFRESH_RESOURCE,
    PRIVILEGE_READ_ROLE,
    PRIVILEGE_CREATE_ROLE,
    PRIVILEGE_UPDATE_ROLE,
    PRIVILEGE_DELETE_ROLE,
    PRIVILEGE_READ_USER,
    PRIVILEGE_CREATE_USER,
    PRIVILEGE_UPDATE_USER,
    PRIVILEGE_DELETE_USER,
    PRIVILEGE_READ_PROVIDER,
    PRIVILEGE_CREATE_PROVIDER,
    PRIVILEGE_UPDATE_PROVIDER,
    PRIVILEGE_DELETE_PROVIDER,
    PRIVILEGE_READ_TRACES,
    PRIVILEGE_CREATE_TRACES,
    PRIVILEGE_UPDATE_TRACES,
    PRIVILEGE_DELETE_TRACES
}